### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 112: invalid continuation byte

### ISSUE THREAD

**Issue by exnx** [cydonia999/Tiny_Faces_in_Tensorflow#11]
Did anyone else get this error as well?  Is it an international text thing?  I'm in the US.

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 112: invalid continuation byte

Thanks for all the help!

**Comment by exnx** [comment]
@cydonia999 Don't suppose you heard of anyone getting an error like this?  Here's the Traceback:

Traceback (most recent call last):
  File "tiny_face_eval.py", line 227, in <module>
    main()
  File "tiny_face_eval.py", line 224, in main
    lw=args.line_width, display=args.display)
  File "tiny_face_eval.py", line 82, in evaluate
    model = tiny_face_model.Model(weight_file_path)
  File "/Users/tvision/Desktop/Tiny_Faces_in_Tensorflow/tiny_face_model.py", line 24, in __init__
    self.mat_blocks_dict, self.mat_params_dict = pickle.load(f)
  File "/Users/tvision/Desktop/Tiny_Faces_in_Tensorflow/tiny-env/bin/../lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by jinglinggithub** [comment]
I have the same problem ;have you solved the problem ?

**Comment by Najjam-786** [comment]
getting same issue, have you resolved it??

**Comment by titlee-97** [comment]
Getting same issue, did you find the solution??
