### ISSUE TITLE
AttributeError: module 'pylab' has no attribute 'frange'

### ISSUE THREAD

**Issue by xnholidayyy** [cydonia999/Tiny_Faces_in_Tensorflow#23]
/home/xinan/.conda/envs/ssh/bin/python3.6 /home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py
/home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:476: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-12-17 10:09:57.123683: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py", line 227, in <module>
    main()
  File "/home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py", line 224, in main
    lw=args.line_width, display=args.display)
  File "/home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py", line 121, in evaluate
    scales = _calc_scales()
  File "/home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py", line 115, in _calc_scales
    scales_down = pl.frange(min_scale, 0, 1.)
AttributeError: module 'pylab' has no attribute 'frange'

**Comment by starsky68** [comment]
> /home/xinan/.conda/envs/ssh/bin/python3.6 /home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py /home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint8 = np.dtype([("qint8", np.int8, 1)]) /home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint8 = np.dtype([("quint8", np.uint8, 1)]) /home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint16 = np.dtype([("qint16", np.int16, 1)]) /home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint16 = np.dtype([("quint16", np.uint16, 1)]) /home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint32 = np.dtype([("qint32", np.int32, 1)]) /home/xinan/.conda/envs/ssh/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:476: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. np_resource = np.dtype([("resource", np.ubyte, 1)]) 2019-12-17 10:09:57.123683: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA Traceback (most recent call last): File "/home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py", line 227, in main() File "/home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py", line 224, in main lw=args.line_width, display=args.display) File "/home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py", line 121, in evaluate scales = _calc_scales() File "/home/xinan/PycharmProjects/2.Tiny_Faces_in_Tensorflow-master/tiny_face_eval.py", line 115, in _calc_scales scales_down = pl.frange(min_scale, 0, 1.) AttributeError: module 'pylab' has no attribute 'frange'

请问如何解决这个问题？
