### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by sreecharan31** [cydonia999/Tiny_Faces_in_Tensorflow#30]
**So, I am getting a TypeError in tiny_face_model.py line 44 ,Kindly help me with this**
`WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/compat/v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "tiny_face_eval.py", line 229, in <module>
    main()
  File "tiny_face_eval.py", line 226, in main
    lw=args.line_width, display=args.display)
  File "tiny_face_eval.py", line 85, in evaluate
    score_final = model.tiny_face(x)
  File "/content/drive/My Drive/Tiny_Faces_in_Tensorflow/tiny_face_model.py", line 207, in tiny_face
    conv = self.conv_block(img, 'conv1', shape=[7, 7, 3, 64], strides=[1, 2, 2, 1], padding="VALID", add_relu=True)
  File "/content/drive/My Drive/Tiny_Faces_in_Tensorflow/tiny_face_model.py", line 126, in conv_block
    weight = self._weight_variable_on_cpu(name, shape)
  File "/content/drive/My Drive/Tiny_Faces_in_Tensorflow/tiny_face_model.py", line 44, in _weight_variable_on_cpu
    initializer = tf.constant_initializer(weights, dtype=self.dtype)
TypeError: __init__() got an unexpected keyword argument 'dtype'`

**Comment by vadimen** [comment]
here is the same model in tf v2.0.1 https://github.com/abtGIT/Tiny_Faces_in_Tensorflow_v2
